/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package booleantostrings;

public class BoolToWord {
    public static String boolToWord(boolean b) {

    return b ? "Yes" : "No";
    }

    public static void main(String[] args) {
    }
}
