/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package booleantostrings;

public class BoolToWord {
    public static String boolToWord(boolean b) {

       String hello = "";

        if (b == true) { 
            hello = "Yes";
        }
        if (b == false) {hello ="No";}

        return hello;
    }

    public static void main(String[] args) {
    }
}
