/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package booleantostrings;

public class BoolToWord {
    public static String boolToWord(boolean b) {
        return "Hello World!";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
    }
}
