/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Katas;
import java.util.regex.*;
import java.util.stream.*;


public class Katas {
    public int opposite(int number) {
        return -number;
    }

    public String pMessage(String name, String owner){
        return name.equals(owner) ? "Hello boss" : "Hello guest"; 
    }

    public int listMin(int[] list) {
        int min = list[0];
        int len = list.length;
        for (int i = 0; i < len; i++) {
            if ( list[i] < min ) {min = list[i];}
        }
        return min;
    }
    public int listMax(int[] list) {
        int max = list[0];
        int len = list.length;
        for (int i = 0; i < len; i++) {
            if ( list[i] > max ) {max = list[i];}
        }
        return max;    }

        public int makeMove(int sticks) {
        // float gameStage = ((float)sticks)/4;
        // String remainder = "0" + String.valueOf(gameStage).substring(1);
        // float take = Float.parseFloat(remainder)*4;
        // return (int) take;
return sticks % 4;
        }

        public int getCount(String str) {
            Pattern pattern = Pattern.compile("[aeiou]", Pattern.CASE_INSENSITIVE);
            Matcher m = pattern.matcher(str);
            int count = 0;
            while (m.find()) {
                count++;
            }
            return count;
        }
        public String disemvowel(String str) {
           return str.replaceAll("(?i)[aeiou]", "");
            // str.chars().map(e -> (char)e.   )
            // return "";
        }
        public int squareDigits(int n) {
            System.out.println("hello");
           String result = String.valueOf(n)
            .chars()
            .map(Character::getNumericValue)
            .map(i -> i*i)
            .mapToObj(j -> ""+j)
            .collect(Collectors.joining(""));
            return Integer.valueOf(result);
        }
}