/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Katas;

public class Katas {
    public int opposite(int number) {
        return -number;
    }

    public String pMessage(String name, String owner){
        return name.equals(owner) ? "Hello boss" : "Hello guest"; 
    }

}
