/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Katas;

import org.junit.Test;

import Katas.Katas;

import static org.junit.Assert.*;

public class KatasTest {
    @Test public void testOpposite() {
        Katas opp = new Katas();
        assertEquals(-1, opp.opposite(1));
    }
    @Test public void testOpposite2() {
        Katas opp = new Katas();
        assertEquals(-14, opp.opposite(14));
    }
    @Test public void testOpposite3() {
        Katas opp = new Katas();
        assertEquals(-34, opp.opposite(34));
    }
}
