/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package oppositenumber;

import org.junit.Test;
import static org.junit.Assert.*;

public class OppositeTest {
    @Test public void testOpposite() {
        Opposite opp = new Opposite();
        assertEquals(-1, opp.opposite(1));
    }
    // @Test public void testOpposite2() {
    //     Opposite opp = new Opposite();
    //     assertEquals(-14, opp.opposite(14));
    // }
    // @Test public void testOpposite3() {
    //     Opposite opp = new Opposite();
    //     assertEquals(-34, opp.opposite(34));
    // }
}
